practohealth_byte_user:
    type: rest
    resource : "@practohealthByteBundle/Controller/UserController.php"

practohealth_byte_post:
    type: rest
    resource : "@practohealthByteBundle/Controller/PostController.php"