services:
#    fit_content.example:
#        class: Fit\ContentBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    fit.helper:
        class: practo\healthByteBundle\Helper\Helper
        arguments:
              - @doctrine
              - @logger

    fit.base_manager:
        class: practo\healthByteBundle\Manager\BaseManager

    fit.user_manager:
        class:  practo\healthByteBundle\Manager\UserManager
        calls:
               - [setHelper, ["@fit.helper"]]

    fit.post_manager:
            class:  practo\healthByteBundle\Manager\PostManager
            calls:
                   - [setHelper, ["@fit.helper"]]

    fit.fit_domain:
              class: practo\healthByteBundle\FitDomain
              scope: request
              arguments: [@request_stack]

    healthByte.openid:
          class: practo\healthByteBundle\Utility\Openid
          arguments:
            - %memcached_host%
            - %memcached_port%
          calls:
            - [setFitDomain,['@?fit.fit_domain=']]