<?php

namespace practo\healthByteBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * postRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class postRepository extends EntityRepository
{
}
