fit_content:
    resource: "@practohealthByteBundle/Resources/config/routing.yml"
    prefix:   /
    type:     rest

fit_non_json:
    resource: "@practohealthByteBundle/Resources/config/routing_nojson.yml"
    prefix:   /

